In [1]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import models, losses
import pandas as pd
import numpy as np
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
documents = [
    "Due to internal crystal structure of the molecules.",
    "nuclears theory  3D structure cube added or removed atoms",
    "Because of count of elements. Mostly about carbon dioxide.",
    "Allotrops such as diamond and graphit they have the same chemical composition but they have a different type of crystal structures.",
    "this name is izonom or isonome this caused from difference connection type of atoms and if is it dipol.",
    "because of elements energy and pyhsical features has different reaction for every composition.",
    "for example water  and ice. both materials are same chemical composition =H2O but physical features are compelety different.and there is bağ .and  this determine  ice or water but i couldnt remember.the diffrence is heat.",
    "Weather and temparature. Because fruit flies' genetics are easily effected affected by temparature and weather. ",
    "Chemical Structure.",
    "We call that allotropism. We may say diamond and grafit as an example.",
    "They are different physical features because same chemical's connection build can be different each other.",
    "We call it isomerism. In isomerism molecules that have the same numbers of the same kinds of atoms but differ in chemical and physical properties.",
    "Same chemical composition has different physical features because they have different crystal structure.",
    "isotopes, becuase they have same atomic number but has different electron numbers.",
    "Change of genetics. Function. dominant genetics and recessive genetics. blend of genetics.modificasion",
    "They called Allotropes. Allotropes are different crystal structures of the same element. Lavoiser showed that, he showed using diamonds and graphite. Burning diamonds and graphite produced the sam gas (CO2) (This was the first example of allotropism)",
    "For example graphit and diomond have pure Carbon(6) but they have different physical compound becasue in this case Carbon(6) can make 4 bond with other Carbon(6) atoms and it changes the physical features . So we can say that in compound , shape of bounding is matters.",
    "differences in their struct differences in their chemical connection",
    "because when atoms combined with each other their  composition is different for example if ""h=h and h-h"" their physical features will be different ",
    "Because the atomic weights and molecular weights of the compounds may be different. The bond types and bond numbers between atoms or molecules may be different.",
    "It might be from temparature. Or it might change by how much material we have. And the ratio between them.",
    "allotrophism. they have different structures. But they include same elements.",
    "Allotropes. They have same chemical composition but different physical features.",
    "It depends on bounds. Bounds depend on locations of elements and we call it allotropism.",
    "Because they have different allotrops which is changes the physical features. For example coil and diamond.",
    "Difference in activation energy in a chemical composition can change the compound in the result. For example: we can burn carbon to gain CO (Carbon monoxide) or to gain CO2 (Carbon dioxide) if we give to the reaction different amount of activation energy we can gain one of them.",
    "When the atom joined, then it lose own properties. So  its characteristic property change. Actually it looks same physcial property but chemical property is different.",
    "Because atoms are in different places and they have different bonds.",
    "Allotrops.",
    "Atoms of the same element are alike( I mean they are also different but has something in common ), but atoms of each element different one from the other in size and weight.",
    " ",
    "When the elements joined,the atoms lose their charachteristic proporties.",
    "Molecular bonds are covalent and ionic lead to different pyhsical properties. Different weight , structure and can oxcid.(I mean oksitlenebilme in Turkish). ",
    "The way that atoms are bonded are different. For example diamond and graphite has the same chemical composition but they have different properities. They are different structures of the same element and it is called allotropy.",
    "Allotropism. Difference in diziliş. Difference in molecular shape of the matter. Like coal and diamond. Those two are only carbons. But their molecular shapes are different.",
    "Allatropism.Its a different crystal structure of an element.An example coal(grafit) and diamond.They are both made by carbon atoms but their crystal structure is different.So their physical features is different. The heat and pressure on coal turning this coal into diamond, and it takes so much time.",
    " ",
    "Because elements should behave of differences.And their weight are should be different.The radioactive is change their characteristic.Every elements feature are difference from others.",
    "Shape, molecular built, freezing point",
    "Like grafit and diamond. They made from carbon but have different physical apperences and when you burn them same gases out come. The reason is chemical bond differences . ",
    "Because they are in different area.(high,P,d)",
    "allotrophism (allotropism). Anthony lavoisier found and explain it. He burned diamound and carbon and he see same element carbon dioxid.Carbon and diamound released same gas.",
    "They are called allotropes. Their features change due to differences in their chemical structures.",
    "Chemical slecture and extends.",
    "They called allotrops. Their physical features was different because they can occure in different orans ( farklı oranlarda birleşebiliyorlar.) . (kimyasal bağları ve çekimleri yüzünden farklılar.)",
    "Distance between cells are different.",
    "If same chemical composition been in different place , these are going to behavior different. It is due to temperature , high from sea distance . I",
    "because of allotrope of elements",
    "Because elements can be make ionik or covalent band. If there are metal and nonmetal, they can be ionik band. If there are two nonmetal, they can be covalent  band. They could be izotop each other. Izotop is, in the same compositions proton counts are same but mass numbers are different.",
    "While working with diamond and graphite Lavoiser noticed that when burned them they released same type gases.(allotropism)Then lieb and Wöhler were about Two different compounds with same percentages of elements.this implies compounds have different arrangements for have different structurals. Because of the stereochemistry.İn a nutshell it is like this they have diiferent physical features because they different arrangement of atoms their 3D structure is different.  ",
    "Allotrop. they have the same atoms but  structure of atoms, their bonds is different each other.",
    "The element particuleses got bounds with different ways.",
    "This differences in the strecture make this. If the same chemical composition but different strecture its become different physical features. ",
    "diiference in chemical connecting type. it names is allotrop if there is chemicial composition but physical features of compounds are due to different it means they are allotrops.",
    "Difference is structure of atoms and arrengement of atoms. And also smell,taste can be different.",
    "Chemical composition and physical features are not connected each other.They just represent  each other.",
    "I think it says allotrop beacuse there arre some carbon but became different mate  it's about their connecting differences for example carbon has 4 connector sometimes it has 4 connects sometimes 2 times double connects so it makes mate different from each other. if it's not about allotrop. Maybe it is about during connecting time's air pressure or temparture differences beacuse they are effecting.",
    "Cells of plants and animals are almost the same, but physically very different from each other.",
    " alllogritms  is  same  chemical composittion but  different compounds because Carbon element is different order so    example diamong and grafiti",
    "Same chemical composition but different physical features of compounds are due to differences in isomerism. Its called Isomerism. Isomerism, the molecules that have same numbers of the same kinds of atoms but difference in chemical and physical properties. Energy are also is a factor in isomerism.",
    "It is called something like allotropes. It is due to differences in molecular structures.",
    "Some of chemical composition are similar but there are difference among their. When the elements are joined, the atoms lose their individual properties and have different properties from the elements they are composed of. A chemical formula is used a quick way to show the composition of compounds. Letters, numbers, and symbols are used to represent elements and the number of elements in each compound.",
    "Because of allotropism . We see that their chemical formulas are the same but their featuers are completly different.",
    "Same chemical composition but different physical features of compounds are due tou differences in period number. Elements which in the same group acts in a similar way as chemical composition. Because the number of atoms they have in the last orbital is same they have same chemical composition. But the total quantity of atoms they have is different so their atomic number is different and they have different physical features of compounds.",
    "Same chemical composition with different physical features gives different results",
    "covid (virus)",
    "allographics composition has different features of compounds for such as elmas and grafit. they have different arragement of atoms and they have different crystial structures. elmas and grafit is same chemical comporisiton but they have different arragment of atoms. so elmas is sert but grafit is yumuşak",
    "Due to bonds in-between. And bonds depends on temperature and shape.",
    "It is due to allotropy. Differences in either bound lines and thus the differences in 3D models of the elements changes the physical features of compounds.",
    "their atoms are attached eachother in different ways.",
    "This is allotropes , ı could not remember correct name of this.",
    "Chemical Structure. For example when we heat some certain compounds, we get a different compound. But they will share the same formula. What differs between those two compounds is their Chemical Structure.",
    "Allatrop . For example diamond and coal. Even though  they are both made of carbon they are totaly different.",
    "They are same in chemical but have differences in physical.They might have different bonds with same atoms which called polarity and dipolarity.",
    "Due to diffrences in how their crystal structures were bonded-made.(Allotropizm)",
    "İf it is the same chemical composition the type of the elements and the numbers of the elements on this composition is same so it depends only how they connected to themself",
    "Compounds by elemental analysis, color, crystal form, melting point, boiling point, taste, smell.",
    "this is called allotropism for example diamond and  k      .  its because of atoms order and any other species",
    "When the elements are joined, the atoms lose their individual properties and have different properties from the elements they are composed of. A chemical formula is used a quick way to show the composition of compounds. Letters, numbers, and symbols are used to represent elements and the number of elements in each compound.",
    "Because of the polarity and dipolarity. When we look at the geometry of compounds, we can see bonds and angles that makes the compound itself. Also different structures as well.",
    "they are due to differences in allotrops' s properties",
    "Chemical bonds cause these different physical features. Compositions may have same kind and many of elements but they might have different physical features. Different kinds of bonds and different bonding styles on same elements causes this differs.",
    "Allotropism. Allotrops have the same proposition in chemical reactions, but different physical features. For instance, graphit and diamond produced same gas (CO2). Lavoisier were explained allotrops first, as well.",
    "because this compounds have different location in space. like mirror or left hand right hand. Sometimes this compounds have different chemical bonds.",
    "due to differences are. ",
    "Due to stereo (3D) structure. It has same atoms but structure is different.",
    "Because their structures are different. The connection type between elements are different. So in spite of same chemical composition and same close formulation they are different.",
    "Allotropes are same chemical composition's different structed styles. For example carbon has two different physical shape because of the heat and force on carbon. If you put carbon in bottom of the down and wait too long it will be diamond. So time, force on it and heat are the most important things in this differences.",
    "isomerism, the existence of molecules that have the same numbers of the same kinds of atoms  hence the same formula but differences  in chemical and physical properties."
]

In [6]:
model = SentenceTransformer('bert-base-nli-mean-tokens')

In [8]:
text_embeddings = model.encode(documents, batch_size = 8, show_progress_bar = True)

Batches: 100%|██████████| 12/12 [00:11<00:00,  1.07it/s]


In [9]:
np.shape(text_embeddings)

(89, 768)

In [10]:
text_embeddings[0]

array([-1.56786051e-02,  3.47296119e-01,  1.08654416e+00,  2.38287672e-01,
        5.15796505e-02, -5.61372757e-01,  2.46481642e-01, -1.73301414e-01,
        3.15272778e-01, -6.50727630e-01, -2.85277158e-01,  1.52841449e-01,
       -6.53187990e-01,  1.24468505e+00,  4.50488687e-01, -3.60727668e-01,
        1.51154725e-02,  1.57394752e-01,  6.67146266e-01,  3.94393085e-03,
        2.25938752e-01, -2.42099479e-01, -1.12513922e-01,  1.86268657e-01,
        5.19483328e-01, -1.09527683e+00, -8.17050859e-02, -1.16437547e-01,
        4.13114578e-01,  7.77155906e-02,  2.12279744e-02, -5.21642864e-01,
       -2.18896955e-01, -6.68444514e-01,  3.84817570e-02,  5.53630471e-01,
       -3.04804146e-01,  5.63205183e-01, -1.33423626e-01,  2.22729981e-01,
       -4.98034030e-01, -4.64908123e-01,  7.14166403e-01,  5.46125591e-01,
       -1.32162607e+00, -5.61858118e-01, -4.34950799e-01,  5.09682119e-01,
       -7.66165495e-01, -6.08490705e-01, -1.35549769e-01, -1.94961965e-01,
        3.20918083e-01,  

In [11]:
similarities = cosine_similarity(text_embeddings)
print('pairwise dense output:\n {}\n'.format(similarities))

pairwise dense output:
 [[0.9999997  0.54292846 0.4939909  ... 0.5209868  0.45293143 0.58978295]
 [0.54292846 0.99999994 0.5562703  ... 0.40635642 0.50900656 0.6435003 ]
 [0.4939909  0.5562703  0.99999994 ... 0.4258808  0.5881676  0.55538285]
 ...
 [0.5209868  0.40635642 0.4258808  ... 0.9999999  0.58030134 0.6088712 ]
 [0.45293143 0.50900656 0.5881676  ... 0.58030134 1.0000002  0.5664292 ]
 [0.58978295 0.6435003  0.55538285 ... 0.6088712  0.5664292  1.0000001 ]]



In [12]:
similarities_sorted = similarities.argsort()

In [13]:
similarities_sorted

array([[70, 36, 30, ..., 50, 79,  0],
       [36, 30, 46, ...,  4, 78,  1],
       [36, 30, 45, ..., 41, 72,  2],
       ...,
       [30, 36, 28, ..., 52, 10, 86],
       [36, 30, 28, ..., 39, 35, 87],
       [36, 30, 28, ..., 59, 11, 88]], dtype=int64)

In [14]:
# Get list of similarity indices i.e. doc at index 0 simialr with doc at index 1169 below.
id_1 = []
id_2 = []
score = []
for index,array in enumerate(similarities_sorted):
    id_1.append(index)
    id_2.append(array[-2])
    score.append(similarities[index][array[-2]])

In [15]:
index_df = pd.DataFrame({'id_1' : id_1,
                          'id_2' : id_2,
                          'score' : score})

In [16]:
index_df

id_1  id_2     score
0      0    79  0.728429
1      1    78  0.702470
2      2    72  0.675812
3      3    33  0.910384
4      4    66  0.815034
..   ...   ...       ...
84    84    40  0.879823
85    85    50  0.800403
86    86    10  0.935735
87    87    35  0.872309
88    88    11  0.963938

[89 rows x 3 columns]